run-name: Pushing image to Docker Hub

name: Push image to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
     
      - name: Log in to Docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ "armijosj" }}
          password: ${{ "dckr_pat_D6kvLu_NbuDnl4jkJG1ubmJ5uzQ" }}

      - name: Docker Server build
        run: |
          docker build ./back_end -t armijosj/familyhub:server
      - name: Docker push
        run: |
          docker push armijosj/familyhub:server

      
        